py_part/socn/socn/accounts/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.views import \
(
    login, logout,
)

urlpatterns = \
[
    url(r'^login/$', login, {'template_name': 'accounts/login.html'},
        name = 'login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'},
        name = 'logout'),
    url(r'^profile/$', views.ViewProfileView.as_view(), name = 'view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.ViewProfileView.as_view(),
        name = 'view_profile'),
    url(r'^profile/edit/$', views.EditProfileView.as_view(),
        name = 'edit_profile'),
    url(r'^register/$', views.RegisterView.as_view(), name = 'register'),
]

py_part/socn/socn/talk/urls.py
from django.conf.urls import url
from socn.talk import views

urlpatterns = \
[
    url(r'^$', views.InfoView.as_view(), name = 'info'),
    url(r'^friends/$', views.FriendsView.as_view(), name = 'friends'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',
        views.ConnectView.as_view(), name = 'connect'),
    url(r'^dialog/(?P<pk>\d+)/$', views.DialogView.as_view(),
        name = 'dialog'),
    url(r'^messages/$', views.MessagesView.as_view(), name = 'messages'),
]

py_part/socn/socn/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = \
[
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('socn.accounts.urls', namespace = 'accounts')),
    url(r'^', include('socn.talk.urls', namespace = 'talk')),
    url(r'^game/', include('socn.games.urls', namespace = 'games')),
    url(r'^trashcan/', include('socn.trashcan.urls', namespace = 'trashcan')),
]

py_part/socn/socn/talk/models.py
from django.db import models
from django.contrib.auth.models import User

class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name = 'owner', null = True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create\
        (
            current_user = current_user
        )
        friend.users.add(new_friend)

    
    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create\
        (
            current_user = current_user
        )
        friend.users.remove(new_friend)


class Message(models.Model):
    sender = models.ForeignKey(User)
    receiver = models.ForeignKey(User, related_name = 'receiver')
    text = models.CharField(max_length = 500)
    read = models.BooleanField()
    date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.sender) + " -> " + str(self.receiver)






    

py_part/socn/socn/talk/forms.py
from django import forms


class MessageForm(forms.Form):
    message = forms.CharField(widget=\
                              forms.Textarea(attrs = {'cols': 50, 'rows': 2}))

py_part/socn/socn/talk/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView
from django.contrib.auth.models import User

from socn.talk.models import Friend, Message
from socn.talk.forms import MessageForm

class InfoView(TemplateView):
    template_name = 'talk/info.html'

class FriendsView(TemplateView):
    template_name = 'talk/friends.html'

    def get(self, request):
        users = User.objects.all().exclude(pk=request.user.pk)
        array1, created = Friend.objects.get_or_create\
                  (current_user = request.user)
        friends = array1.users.all()

        args = {'users': users, 'friends': friends}
        return render(request, self.template_name, args)


class ConnectView(TemplateView):
    def get(self, request, operation, pk):
        friend = User.objects.get(pk=pk)
        if operation == 'add':
            Friend.make_friend(request.user, friend)
        elif operation == 'remove':
            Friend.lose_friend(request.user, friend)
        return redirect(reverse('talk:friends'))


class DialogView(TemplateView):
    template_name = 'talk/dialog.html'

    def get(self, request, pk):
        form = MessageForm()
        friend = User.objects.get(pk = pk)
        messages = Message.objects.filter\
            (
                sender = request.user,
                receiver = friend,
            )\
        	|\
        	Message.objects.filter\
            (
                receiver = request.user,
                sender = friend,
            )

        messages = messages.order_by("-date")
        args = {'messages': list(messages), 'form': form, 'friend': friend}

        Message.objects.filter\
            (
                receiver = request.user,
                sender = friend,
            ).update(read=True)
        return render(request, self.template_name, args)

    def post(self, request, pk):
        form = MessageForm(request.POST)
        friend = User.objects.get(pk = pk)

        if form.is_valid():
            message = Message()
            message.sender = request.user
            message.receiver = friend
            message.read = False
            message.text = form.cleaned_data['message']
            message.save()
        return redirect(reverse('talk:dialog', kwargs={'pk': pk}))


class MessagesView(TemplateView):
    template_name = 'talk/messages.html'

    def get(self, request):
        lot = {}
        dialogs = []
        messages = Message.objects.filter(receiver = request.user) |\
                   Message.objects.filter(sender = request.user)
        messages = messages.order_by("-date")

        for message in messages:
            if message.sender == request.user:
                friend = message.receiver
            else:
                friend = message.sender
                
            if not friend in lot:
                lot[friend] = 0
                dialogs.append([friend, 0])

            if message.receiver == request.user and not message.read:
                lot[friend] += 1

        for it in dialogs:
            it[1] = lot[it[0]]

        args = {'dialogs': dialogs}
        return render(request, self.template_name, args)
            
        

py_part/socn/socn/talk/templates/talk/dialog.html
{% extends 'base.html' %}

{% block body %}
<style>
	div.container1
	{
		width:600px;
		word-wrap: break-word;
		margin: auto;
		border: 2px solid #FCFCFC;
		background: #FCFCFC;
	}
	
	form
	{
		text-align: center;
	}

	div.unread
	{
		width: 400px;
		border: 1px solid #DDDDFF;
		background: #DDDDFF;
		margin-top: 10px;
		border-radius: 5px;
	}

	div.read
	{
		width: 400px;
		border: 1px solid #FCFCFC;
		background: #F8F0F0;
		margin-top: 10px;
		border-radius: 5px;
	}
</style>
	<div class="container1">
		<p align="right">
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<p align="center">
				<button type="submit">Submit</button>
			</p>
		</p>
		</form>

		<p style="text-align:left;">
		<font size="6" align="right">Me</font>
		<span style="float:right;">
		<font size="6">{{ friend }}</font>
		</span>
		</p>

		{% for mes in messages %}


			{% if mes.read %}
				<div class="read"
			{% else %}
				<div class="unread"
			{% endif %}

				{% if mes.sender == request.user %}
					style="float:left"><p align="left">
				{% else %}
					style="float:right"><p align="right">
				{% endif %}
					<font size="3">{{ mes.text }}</font></p>
				</div>

		{% endfor %}
									
{% endblock %}

py_part/socn/socn/talk/templates/talk/friends.html
{% extends 'base.html' %}

{% block body %}
	<div class="container">
		<div class="col-md-5">
			<h2>Friends</h2>
			{% for friend in friends %}
				<div class="btn-group">
					<a href="{% url 'talk:connect' operation='remove' pk=friend.pk %}"
						class="btn btn-default">
						Remove
					</a>
					<a href="{% url 'talk:dialog' pk=friend.pk %}"
						 class="btn btn-default">
						Chat
					</a>
				</div>
				&emsp;
				<a href="{% url 'accounts:view_profile' pk=friend.pk %}">
					<font size="5">{{ friend }}</font>
				</a>
				<br>
				<br>
			{% endfor %}
		</div>

		<div class="col-md-6">
			<h2>Other People</h2>
			{% for user in users %}
				<a href="{% url 'talk:connect' operation='add' pk=user.pk %}">
					{% if not user in friends %}
						<button type="button" class="btn btn-success">
					{% else %}
						<button type="button" class="btn btn-success disabled">
					{% endif %}
							Add Friend
						</button>
				</a>
				&emsp;
				<a href="{% url 'accounts:view_profile' pk=user.pk %}">
					<font size="5">{{ user }}</font>
				</a>
				<br>
				<br>
			{% endfor %}
		</div>
	</div>
{% endblock %}

py_part/socn/socn/talk/templates/talk/info.html
{% extends 'base.html' %}

{% block body %}
	<div class="container">
		<h1 align="center">Welcome!</h1>
		<div class="jumbotron">
      <!--
			<h2>Alex Network</h2>
			<p><b>Author:</b> Aleksey Slutskiy</p>
			<p><b>Headquarters:</b> Saratov SU</p>
      -->

      {% load static %}
      <img src="{% static 'djangologo.png' %}" width="200" height="200"
           style="float:left; margin-right: 20px;">
      <p>&nbsp;&nbsp;&nbsp;&nbsp;Hi! My name's Aleksey. I made the simple web-site.
      I try to learn any web-programming cool stuff and add it to this project.
      You could say It's my platform for code learning.</p>

      <p>&nbsp;&nbsp;&nbsp;&nbsp;I've already implemented the basic social network,
        where you can only send messages and add friends.
        So far, I'm not very good at front-end developing,
        so the layout could be ugly now :-) I've just started.
        Also I learn javascript and
        I made couple simple games with html-canvas.</p>

      <p style="display:inline;">&nbsp;&nbsp;&nbsp;&nbsp;
        You <u>need to register</u> to view my work.
        It's pretty easy, less than 1 minute.
        Check this out! I appreciate you tips, suggestions and questions.
        You can always drop me a line at
        <p style="display:inline;font-family: Arial;font-size:19;">
          slutskiyad@gmail.com.
        </p>
      </p>

      <p>&nbsp;&nbsp;&nbsp;&nbsp;Thank you for your attention.</p>
		</div>
	</div>
{% endblock %}

py_part/socn/socn/talk/templates/talk/messages.html
{% extends 'base.html' %}

{% block body %}
<style>
	div.container2
  {
    width:600px;
    margin: auto;
	padding-left: 30px;
    border: 2px solid #F0F0F0;
    background: #FCFCFC;
  }
</style>

	<div class="container2">
		{% for dialog in dialogs %}
			<a href="{% url 'talk:dialog' pk=dialog.0.pk %}">
				<h3>
					{{ dialog.0 }}
					{% if dialog.1 > 0 %}
						[{{ dialog.1 }}]
					{% endif %}
				</h3>
					
			</a>
		{% endfor %}
{% endblock %}