py_part/socn/socn/accounts/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.views import \
(
    login, logout,
)

urlpatterns = \
[
    url(r'^login/$', login, {'template_name': 'accounts/login.html'},
        name = 'login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'},
        name = 'logout'),
    url(r'^profile/$', views.ViewProfileView.as_view(), name = 'view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.ViewProfileView.as_view(),
        name = 'view_profile'),
    url(r'^profile/edit/$', views.EditProfileView.as_view(),
        name = 'edit_profile'),
    url(r'^register/$', views.RegisterView.as_view(), name = 'register'),
]

py_part/socn/socn/games/urls.py
from django.conf.urls import url
from socn.games import views
from django.views.generic import TemplateView


urlpatterns = \
[
    url(r'^ranklist/$', views.ranklist, name = 'ranklist'),
    url(r'^myapi_(?P<item>[a-z0-9]+)/$', views.myapi, name = 'myapi'),
]


              

py_part/socn/socn/talk/urls.py
from django.conf.urls import url
from socn.talk import views

urlpatterns = \
[
    url(r'^$', views.InfoView.as_view(), name = 'info'),
    url(r'^friends/$', views.FriendsView.as_view(), name = 'friends'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',
        views.ConnectView.as_view(), name = 'connect'),
    url(r'^dialog/(?P<pk>\d+)/$', views.DialogView.as_view(),
        name = 'dialog'),
    url(r'^messages/$', views.MessagesView.as_view(), name = 'messages'),
]

py_part/socn/socn/trashcan/urls.py
from django.conf.urls import url
from socn.trashcan import views


urlpatterns = [
    url(r'^$', views.scroll, name = 'scroll'),
    url(r'^snake$', views.snake, name = 'snake'),
    url(r'^tic5$', views.tic5, name = 'tic5'),
]

py_part/socn/socn/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = \
[
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('socn.accounts.urls', namespace = 'accounts')),
    url(r'^', include('socn.talk.urls', namespace = 'talk')),
    url(r'^game/', include('socn.games.urls', namespace = 'games')),
    url(r'^trashcan/', include('socn.trashcan.urls', namespace = 'trashcan')),
]

py_part/socn/socn/games/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.models import User
import json
from django.views.decorators.csrf import csrf_exempt


def ranklist(request):
    data = {'users': User.objects.all()}
    return render(request, 'games/ranklist.html', data)


def cors_response(data):
    response = JsonResponse(data)
    response["Access-Control-Allow-Origin"] = "http://127.0.0.1:2000"
    response["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS"
    response["Access-Control-Max-Age"] = "1000"
    response["Access-Control-Allow-Headers"] = "*"
    response["Access-Control-Allow-Credentials"] = "true"
    return response
    

@csrf_exempt
def myapi(request, item):        
    if (item == 'username'):
        data = {'username': str(request.user)}
        
        return cors_response(data)
    elif item == 'winner':
        winner_name = json.loads(request.body.decode())['username']
        winner_obj = User.objects.get(username=winner_name)
        winner_obj.userprofile.score += 1
        winner_obj.userprofile.save()
        
        return cors_response({'status': 'OK'})

                        
                            

py_part/socn/socn/games/templates/base.html
<html>
  <head>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    
    <meta charset="utf-8">

    {% load static %}
    <link rel="stylesheet" href="{% static 'base.css' %}">

    <title>Aleks's Network</title>
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>-->
    <script type="text/javascript" src="{% static 'base.js' %}"></script>

    <div class="header-div">
      <p class="header-p"><a class="header-a" href="{% url 'talk:info' %}">A L E K S ' S</a></p>
    </div>
    <div class="middle">
      <div class="middle-left">
        <div class="my-navbar">
          <ul class="navbar-ul">
            {% if user.is_authenticated %}
              <li><a class="navbar-a" href="{% url 'talk:messages' %}">Messages</a></li>
              <li><a class="navbar-a" href="{% url 'talk:friends' %}">Friends</a></li>
              
              <div class="dropdown">
                <a class="navbar-a" onclick="myfunc(this)">
                  Profile<p style="float:right;" align="right">&#8711;</p>
                </a>
                <div class="dropdown-content">
                  <li><a style="display: block;" class="navbar-a"
                         href="{% url 'accounts:view_profile' %}">
                      View</a>
                  </li>
                  <li><a style="display: block;" class="navbar-a"
                         href="{% url 'accounts:edit_profile' %}">
                      Edit</a>
                  </li>
                </div>
              </div>

              <div class="dropdown">
                <a class="navbar-a" id="lah" onclick="myfunc(this)">
                  Connect 4<p style="float:right;" align="right">&#8711;</p>
                </a>
                <div class="dropdown-content">
                  <li><a style="display: block;" class="navbar-a"
                         href="127.0.0.1:5000/connect4">
                         <!--href="http://tuna.com.ru/connect4"-->
                             
                      Multiplayer</a>
                  </li>
                  <li><a style="display: block;" class="navbar-a"
                         href="{% url 'games:ranklist' %}">
                      Ranklist</a>
                  </li>
                </div>
              </div>
              <br><br><br><br>
              <li><a class="navbar-a" href="{% url 'accounts:logout' %}">
                  Log out</a>
              </li>
            {% else %}
              <li><a class="navbar-a" href="{% url 'accounts:register' %}">
                  Register</a>
              </li>
              <li><a class="navbar-a" href="{% url 'accounts:login' %}">
                  Log in</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
        
      <div class="middle-right">
        {% block body %}
        <h1>BODY PATTERN</h1>
        {% endblock %}
      </div>      
    </div>
    
  </body>

  <script src="http://code.jquery.com/jquery-3.2.1.min.js"
          integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossorigin="anonymous"></script>
</html>

py_part/socn/socn/games/templates/old_base.html
<html>
	<head>
		<link rel="stylesheet"
					href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
					integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
					crossorigin="anonymous">
		{% block head %}
			<title>Social Network</title>
		{% endblock %}

	</head>

	<body>
		<br>
		<div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
										data-toggle="collapse"
										data-target="#navbar"
										aria-expanded="false"
										aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'talk:info' %}">Alex Network</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
							{% if user.is_authenticated %}
								<li><a href="{% url 'talk:messages' %}">
										Messages</a>
								</li>
								<li><a href="{% url 'talk:friends' %}">
										Friends</a>
								</li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown"
										 role="button" aria-haspopup="true"
										 aria-expanded="false">Profile
										<span class="caret"></span></a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'accounts:view_profile' %}">
												View</a>
										</li>
										<li><a href="{% url 'accounts:edit_profile' %}">
												Edit</a>
										</li>
									</ul>									
								</li>

                <li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown"
										 role="button" aria-haspopup="true"
										 aria-expanded="false">Games
										<span class="caret"></span></a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'games:snake' %}">
												Snake</a>
										</li>
										<li><a href="{% url 'games:tic5' %}">
												Tic-Tac-5</a>
										</li>
									</ul>									
								</li>
							{% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
							{% if user.is_authenticated %}
								<p class="navbar-text">{{ user }}</p>
  	            <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
							{% else %}
								<li><a href="{% url 'accounts:register' %}">Register</a></li>
								<li><a href="{% url 'accounts:login' %}">
										Log in</a>
								</li>
							{% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
		</div>

		{% block body %}
			<h1>Base</h1>
		{% endblock %}
	</body>

	<script src="http://code.jquery.com/jquery-3.2.1.min.js"
					integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
					crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
					integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
					crossorigin="anonymous"></script>
</html>