py_part/socn/socn/trashcan/urls.py
from django.conf.urls import url
from socn.trashcan import views


urlpatterns = [
    url(r'^$', views.scroll, name = 'scroll'),
    url(r'^snake$', views.snake, name = 'snake'),
    url(r'^tic5$', views.tic5, name = 'tic5'),
]

py_part/socn/socn/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = \
[
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('socn.accounts.urls', namespace = 'accounts')),
    url(r'^', include('socn.talk.urls', namespace = 'talk')),
    url(r'^game/', include('socn.games.urls', namespace = 'games')),
    url(r'^trashcan/', include('socn.trashcan.urls', namespace = 'trashcan')),
]

py_part/socn/socn/trashcan/models.py
from django.db import models

# Create your models here.

py_part/socn/socn/trashcan/views.py
from django.shortcuts import render

# Create your views here.
def scroll(request):
    return render(request, 'trashcan/scroll.html')

def snake(request):
    return render(request, 'trashcan/snake.html')

def tic5(request):
    return render(request, 'trashcan/tic5.html')

py_part/socn/socn/trashcan/templates/trashcan/scroll.html
<html>
  <head>
    <title>Trashcan</title>
  </head>
  <body>
    <ul>
      <li><a href="{% url 'trashcan:snake' %}">Snake</a></li>
      <li><a href="{% url 'trashcan:tic5' %}">Tic Tac 5</a></li>
    </ul>
  </body>
</html>

py_part/socn/socn/trashcan/templates/trashcan/snake.html
{% extends 'base.html' %}

{% block head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'games/snake.css' %}">
{% endblock %}

{% block body %}
  <script type="text/javascript" src="{% static 'games/snake.js' %}">
  </script>
{% endblock %}





		

py_part/socn/socn/trashcan/templates/trashcan/tic5.html
{% extends 'base.html' %}

{% block head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'games/tic5.css' %}">
{% endblock %}

{% block body %}
  <script type="text/javascript" src="{% static 'games/tic5.js' %}">
  </script>
{% endblock %}




    